### ISSUE TITLE
Feature Request: Woke buck transaction history

### ISSUE THREAD

**Issue by Quillenator** [chicklightning/WokebucksBot#3]
As a user I can query a user's woke buck transaction history. Call it $wokehistory.

Would require transactional history to be stored in the database, along with a way to query and format the data in a readable way.

A potential format example:

$wokehistory @user
Current woke bucks: $N
Granted $N woke bucks on MM/DD/YY
Subtracted $N woke bucks on MM/DD/YY
Starting balance of $N woke bucks on MM/DD/YY

**Comment by chicklightning** [comment]
"Receipts" feature

**Comment by chicklightning** [comment]
Implemented feature but only keep the last 10 logs, don't wanna pay for a shitton of storage or a lot of processing power.
