### ISSUE TITLE
Feature Request: Who is woke?

### ISSUE THREAD

**Issue by Quillenator** [chicklightning/WokebucksBot#9]
As a user, I would like to know who is woke and who is not.

$whoiswoke

user1, user2, user3 are woke
user4, user5, user 6 are not woke

This should likely pull the list of active users, pulling the entire server would be a huge list.

**Comment by chicklightning** [comment]
Already implemented with the leaderboard, `$leaderboard` gives the top 3 most woke for the server and `$skeeterboard` gives the top 3 least woke for the server.
